AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ProbeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: antares-dev-cfprobe5
  Dist:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: false
        Comment: probe A
        DefaultRootObject: index.html
        HttpVersion: http2
        Origins:
          - Id: site
            DomainName: !GetAtt ProbeBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ""
          - Id: api
            DomainName: probe.example.execute-api.us-east-1.amazonaws.com
            OriginPath: /dev
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols: [TLSv1.2]
        DefaultCacheBehavior:
          TargetOriginId: site
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
