AWSTemplateFormatVersion: "2010-09-09"
Resources:
  OAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: antares-probe-oac2
        SigningProtocol: SIGV4
        SigningBehavior: always
        OriginAccessControlOriginType: s3
