AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ProbeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: antares-dev-cfprobe
  Dist:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: false
        Comment: probe
        DefaultRootObject: index.html
        HttpVersion: http2
        Origins:
          - Id: site
            DomainName: !GetAtt ProbeBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultCacheBehavior:
          TargetOriginId: site
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
